### ISSUE TITLE
Link auf verständliche Einführung ergänzen?

### ISSUE THREAD

**Issue by LeSpocky** [netz39/blockchain-infosite#9]
Fand den Artikel [Warum Bitcoin so viel Energie braucht](https://www.spektrum.de/kolumne/was-es-mit-dem-hohen-energieverbrauch-von-bitcoin-auf-sich-hat/2182965) recht gut verständlich. An die Liste unten anhängen?

**Comment by penguineer** [comment]
Genau, für sowas kannst Du auch direkt einen PR machen. (Das geht ja auch in der GitHub-UI und ist schnell erledigt. :) )

**Comment by penguineer** [comment]
Wenn es eine Einführung ist, sollte der Link vielleicht nicht einfach in die Liste, sondern unter "Was ist eine Blockchain" auftauchen?
